/**
 * SSOT for module-level hardcoded values (strings, numbers, regex, headers, URLs).
 * Nested by source module for navigation; `shared` holds cross-cutting duplicates.
 *
 * Usage in a module:
 *   import { CONSTANTS } from './constants.js';
 *   const { EMPTY_VALUE, FILE_ENCODING } = CONSTANTS.shared;
 *   const { … } = CONSTANTS.main;
 */

const SHARED = {
  EMPTY_VALUE: '',
  FILE_ENCODING: 'utf8' as BufferEncoding,
  NEWLINE: '\n',
  JSON_INDENT: 2,
  DOUBLE_NEWLINE: '\n\n',
  SINGLE_SPACE: ' ',
  FILE_PATH_EXTENSION_SEPARATOR: '.',
  RELATIVE_PATH_SEPARATOR: '/',
  KEY_VALUE_SEPARATOR: '=',
  LIST_SEPARATOR: ', ',

  YOUTUBE_BASE_URL: 'https://www.youtube.com',
  YOUTUBE_ORIGIN_SLASH: 'https://www.youtube.com/',
  YOUTUBE_WWW_HOST: 'www.youtube.com',
  YOUTUBE_HOST_MARK: 'youtube.com',
  YOUTU_BE_HOST_MARK: 'youtu.be',
  GOOGLE_HOST_MARK: 'google.com',
  YOUTUBE_COOKIE_DOMAIN: '.youtube.com',
  WATCH_QUERY_PREFIX: 'https://www.youtube.com/watch?v=',
  PLAYLIST_PATH_PREFIX: 'https://www.youtube.com/playlist?list=',

  YOUTUBE_INITIAL_DATA_MARKER: 'ytInitialData = ',
  YOUTUBE_INITIAL_PLAYER_RESPONSE_MARKER: 'ytInitialPlayerResponse = ',
  YOUTUBE_PRETTY_PRINT_QUERY: 'prettyPrint=false',

  VIDEO_ID_PATTERN: /^[A-Za-z0-9_-]{11}$/,
  VIDEO_ID_CAPTURE_GROUP: 1,

  DEFAULT_LANGUAGE: 'en',
  DEFAULT_REGION: 'US',
  DEFAULT_WEB_API_KEY: 'AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8',
  WEB_CLIENT_NAME: 'WEB',
  BROWSER_USER_AGENT:
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36',

  // Brace/quote scan: open delimiter is also a string for indexOf; codes for scanners.
  OPEN_BRACE: '{',
  OPEN_BRACE_CODE: '{'.charCodeAt(0),
  CLOSE_BRACE_CODE: '}'.charCodeAt(0),
  DOUBLE_QUOTE_CODE: '"'.charCodeAt(0),
  ESCAPE_CHARACTER_CODE: '\\'.charCodeAt(0),
  BRACE_DEPTH_COMPLETE: 0,

  // Shared Innertube client pacing (player + channel continuations).
  CLIENT_ATTEMPT_DELAY_MS: 350,

  JSON_PARSE_ERROR_PREFIX: 'Could not parse',
  JSON_INCOMPLETE_ERROR_PREFIX: 'Could not parse complete',
};

export const CONSTANTS = {
  shared: SHARED,

  agent: {
    AGENT_INPUT_HEADER: 'System Prompt:',
    AGENT_VIDEO_LABEL: 'Video:',
    AGENT_LANGUAGE_LABEL: 'Language:',
    AGENT_TRANSCRIPT_HEADER: 'Transcript:',
    AGENT_COMMAND_NOT_FOUND: 'ENOENT',
    // Long skill packages (multi-skill transcripts) can exceed 5 minutes on Grok/Codex.
    AGENT_COMMAND_TIMEOUT_MS: 900_000,
    AGENT_OUTPUT_TAG: 'Agent',
    PROMPT_ARG_PLACEHOLDER: '__PROMPT__',
    LONG_ARG_SUMMARY_LIMIT: 120,
    LONG_ARG_SUMMARY_PREFIX_LENGTH: 117,
    CODEX_SPARK_MODEL: 'gpt-5.3-codex-spark',
    PROMPT_CONSUMING_FLAGS: ['-p', '--prompt', '--single', '--print'],
  },

  agentModels: {
    MODEL_FLAG_PLACEHOLDER: '__MODEL__',
    SPAWN_TIMEOUT_MS: 45_000,
    DEFAULT_LABEL_MARK: '(default)',
    STAR_PREFIX: '*',
  },

  captions: {
    TRACK_KIND_AUTO: 'asr',
    TRACK_KIND_MANUAL: 'manual',
    LANGUAGE_TOKEN_WILDCARD: 'all',
    FALLBACK_LANGUAGE_TAG: 'und',
    VSS_ID_LEADING_DOT: /^\./,
    VSS_ID_DOT_REPLACER: /\./g,
    CAPTION_FORMAT_QUERY_PARAM: 'fmt',
    AUTO_LANGUAGE_PREFIX: 'a-',
  },

  channel: {
    YOUTUBE_BROWSE_API_PATH: '/youtubei/v1/browse',
    DEFAULT_WEB_CLIENT_VERSION: '2.20250925.01.00',
    WEB_CLIENT_ID: '1',
    CHANNEL_HANDLE_PATTERN:
      /^https?:\/\/(?:www\.)?youtube\.com\/@([A-Za-z0-9._-]+)(?:\/(videos|streams|shorts|playlists|featured|about))?\/?(?:[?#].*)?$/i,
    CHANNEL_ID_PATH_PATTERN:
      /^https?:\/\/(?:www\.)?youtube\.com\/channel\/(UC[A-Za-z0-9_-]+)(?:\/(videos|streams|shorts|playlists|featured|about))?\/?(?:[?#].*)?$/i,
    CHANNEL_CUSTOM_PATH_PATTERN:
      /^https?:\/\/(?:www\.)?youtube\.com\/(?:c|user)\/([A-Za-z0-9._-]+)(?:\/(videos|streams|shorts|playlists|featured|about))?\/?(?:[?#].*)?$/i,
    CHANNEL_AT_PREFIX: '@',
    CHANNEL_VIDEOS_TAB: 'videos' as const,
    CHANNEL_SHORTS_TAB: 'shorts' as const,
    CHANNEL_BULK_FOLDER_PREFIX_VIDEOS: 'channel-',
    CHANNEL_BULK_FOLDER_PREFIX_SHORTS: 'shorts-',
    FOLDER_UNSAFE_PATTERN: /[^A-Za-z0-9._-]+/g,
    MAX_CONTINUATION_PAGES: 40,
    API_KEY_PATTERN: /"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"/,
    CLIENT_VERSION_PATTERN: /"INNERTUBE_CONTEXT_CLIENT_VERSION"\s*:\s*"([^"]+)"/,
    VISITOR_DATA_PATTERN: /"visitorData"\s*:\s*"([^"]+)"/,
  },

  cli: {
    DEFAULT_FORMAT_TOKEN: 'vtt' as const,
    DEFAULT_LANGUAGE_TOKEN: 'en' as const,
    DEFAULT_OUTPUT_FOLDER: './scraped-yt',
    DEFAULT_INTERACTIVE_OUTPUT: 'default',
    DEFAULT_PROMPT_CHOICE: 'default',
    OPTION_TOKEN_PREFIX: '--',
    OPTION_WITH_VALUE_FORMAT: 'format',
    OPTION_WITH_VALUE_LANG: 'lang',
    OPTION_WITH_VALUE_OUT_DIR: 'out-dir',
    OPTION_WITH_VALUE_OUTPUT_FORMAT: 'output-format',
    OPTION_WITH_VALUE_AGENT: 'agent',
    OPTION_WITH_VALUE_MODEL: 'model',
    OPTION_WITH_VALUE_REASONING_EFFORT: 'reasoning-effort',
    OPTION_WITH_VALUE_SYSTEM_PROMPT: 'system-prompt',
    OPTION_WITH_VALUE_COOKIES: 'cookies',
    OPTION_WITH_VALUE_URL: 'url',
    OPTION_WITH_VALUE_CONCURRENCY: 'concurrency',
    OPTION_WITH_VALUE_MAX_VIDEOS: 'max-videos',
    OPTION_BOOLEAN_AUTO: 'auto',
    OPTION_BOOLEAN_STDOUT: 'stdout',
    OPTION_BOOLEAN_HELP: 'help',
    NONE_AGENT_VALUE: 'none',
    CLI_OPTION_SEPARATOR: ',',
    BOOLEAN_TRUE: 'true',
    BOOLEAN_ONE: '1',
    BOOLEAN_YES: 'yes',
    BOOLEAN_FALSE: 'false',
    BOOLEAN_ZERO: '0',
    BOOLEAN_NO: 'no',
    PROMPT_CHOICE_CUSTOM: 'custom',
    OUTPUT_FORMAT_TXT: 'txt',
    OUTPUT_FORMAT_MD: 'md',
    OUTPUT_FORMAT_JSON: 'json',
    OUTPUT_FORMAT_JSONL: 'jsonl',
    ABORTED_LABEL: 'Aborted',
    INTRO_MESSAGE: 'yt-captions-mini-ai options',
    OUTRO_MESSAGE: 'Ready',
    PROMPT_SUBTITLE_FORMATS: 'Select subtitle formats',
    PROMPT_LANGUAGE_TOKENS: 'Language tokens',
    PROMPT_ALLOW_AUTO: 'Allow auto captions',
    PROMPT_OUTPUT_FORMAT: 'Output format',
    PROMPT_OUTPUT_FOLDER: 'Output folder',
    PROMPT_STDOUT_ONLY: 'Write to stdout only',
    PROMPT_LOCAL_AGENT: 'Select local agent',
    PROMPT_AGENT_MODEL: 'Select model for this agent (from its CLI)',
    PROMPT_REASONING_EFFORT: 'Reasoning effort (grok/agent only; optional)',
    PROMPT_SYSTEM_PROMPT_MODE: 'System prompt',
    PROMPT_CUSTOM_SYSTEM_PROMPT: 'Paste system prompt',
    PROMPT_COOKIES_PATH: 'Netscape cookies.txt path (optional)',
    PROMPT_YOUTUBE_INPUT: 'YouTube URL or ID',
    LABEL_SKIP_LOCAL_AGENT: 'Skip local agent',
    LABEL_KEEP_SOURCE_FORMAT: 'Keep source format',
    LABEL_OFFICIAL_SKILL_PROMPT: 'Official skill prompt (Recommended)',
    LABEL_CUSTOM_PROMPT: 'Custom prompt',
    LABEL_CLI_DEFAULT_MODEL: 'CLI default (no -m)',
    LABEL_SKIP_REASONING_EFFORT: 'Skip (CLI default effort)',
    USAGE_TEXT:
      'Usage: npm start url=<youtube-url|@channel|playlist|video-id> [format=vtt,srt] [lang=en] [auto] [stdout] [out-dir=./scraped-yt] [output-format=txt|md|json|jsonl] [cookies=./cookies.txt] [concurrency=4] [max-videos=N] [agent=codex|grok|devin|claude|gemini|kiro|kimi|agent|cursor] [model=<id>] [reasoning-effort=high|medium|low] [system-prompt="..."]',
    DEFAULT_BULK_CONCURRENCY: 4,
    MIN_BULK_CONCURRENCY: 1,
    MAX_BULK_CONCURRENCY: 32,
    MIN_MAX_VIDEOS: 1,
    HTTP_SCHEME_PREFIX: 'http://',
    HTTPS_SCHEME_PREFIX: 'https://',
  },

  cookies: {
    COOKIE_FIELD_SEPARATOR: '\t',
    COOKIE_PAIR_SEPARATOR: '; ',
    COOKIE_COMMENT_PREFIX: '#',
    COOKIE_HTTPONLY_PREFIX: '#HttpOnly_',
    DOMAIN_ATTRIBUTE_NAME: 'domain',
    MIN_NETSCAPE_FIELD_COUNT: 7,
    NETSCAPE_DOMAIN_INDEX: 0,
    NETSCAPE_NAME_INDEX: 5,
    NETSCAPE_VALUE_INDEX: 6,
    SET_COOKIE_NAME_VALUE_INDEX: 0,
  },

  http: {
    USER_AGENT_HEADER: 'User-Agent',
    ACCEPT_LANGUAGE_HEADER: 'Accept-Language',
    ACCEPT_HEADER: 'Accept',
    CONTENT_TYPE_HEADER: 'Content-Type',
    REFERER_HEADER: 'Referer',
    COOKIE_HEADER: 'Cookie',
    SET_COOKIE_HEADER: 'set-cookie',
    RETRY_AFTER_HEADER: 'retry-after',
    COOKIE_HEADER_LOWER: 'cookie',
    ACCEPT_LANGUAGE: 'en-US,en;q=0.8',
    ACCEPT_ALL: '*/*',
    CONTENT_TYPE_JSON: 'application/json',
    HTTP_METHOD_POST: 'POST',
    HTTP_STATUS_SUCCESS_START: 200,
    HTTP_STATUS_REDIRECT_START: 300,
    HTTP_STATUS_TOO_MANY_REQUESTS: 429,
    HTTP_STATUS_BAD_GATEWAY: 502,
    HTTP_STATUS_SERVICE_UNAVAILABLE: 503,
    HTTP_STATUS_GATEWAY_TIMEOUT: 504,
    MAX_RETRY_ATTEMPTS: 4,
    BASE_RETRY_DELAY_MS: 1500,
    MAX_RETRY_DELAY_MS: 20_000,
  },

  log: {
    LOG_TAG_INFO: 'INFO',
    LOG_TAG_WARN: 'WARN',
    LOG_TAG_ERR: 'ERR',
    LOG_TAG_PREFIX: '[',
    LOG_TAG_SUFFIX: '] ',
  },

  main: {
    SOURCE_WATCH_ID_PATTERN: /[?&]v=([A-Za-z0-9_-]{11})/,
    SOURCE_SHORTS_ID_PATTERN: /\/shorts\/([A-Za-z0-9_-]{11})/,
    VIDEO_INDEX_OFFSET: 1,
    SHORT_DELAY_MS: 450,
    // Spacing between bulk workers only when concurrency is 1 (serial mode).
    SERIAL_VIDEO_DELAY_MS: 150,
    EXIT_CODE_FAILURE: 1,
    LOG_INNERTUBE_FIRST_PREFIX: 'innertube-first tracks found:',
    LOG_HTML_FALLBACK_PREFIX: 'watch HTML fallback tracks found:',
    LOG_BULK_CONCURRENCY: 'bulk concurrency:',
    LOG_TRACKS_NOT_FOUND: 'none',
    LOG_PLAYLIST_NOT_FOUND: 'No playlist videos found for',
    LOG_NO_TRACK: 'No suitable caption track for',
    LOG_EMPTY_OUTPUT: 'No transcript cues found for',
    LOG_INVALID_VIDEO_ID: 'Invalid video id/url:',
    LOG_MISSING_PLAYER_PAYLOAD: 'Could not find ytInitialPlayerResponse for',
    LOG_MISSING_DATA_PAYLOAD: 'Could not find ytInitialData for playlist',
    LOG_PLAYLIST_FETCHED: 'Playlist',
    LOG_PLAYLIST_COUNT_MESSAGE: 'videos extracted',
    LOG_CHANNEL_FETCHED: 'Channel',
    LOG_CHANNEL_COUNT_MESSAGE: 'items extracted from',
    LOG_CHANNEL_URL: 'channel tab url',
    LOG_CHANNEL_OUT_DIR: 'bulk output folder',
    LOG_VIDEO_PROGRESS: 'processing video',
    LOG_PLAYLIST_VIDEO_SKIPPED: 'Skipping',
    LOG_CHANNEL_NOT_FOUND: 'No channel items found for',
    LOG_TRACKS_PREFIX: 'tracks found:',
    LOG_FALLBACK_TRACKS_PREFIX: 'fallback tracks found:',
    LOG_MULTI_CLIENT_TRACKS_PREFIX: 'multi-client tracks found:',
    LOG_WATCH_HTML_SKIPPED: 'watch HTML unavailable; using multi-client player API',
    LOG_COOKIES_LOADED: 'Loaded Netscape cookies:',
    LOG_VIDEO_OUTPUT_TEMPLATE: 'Saved subtitles:',
    LOG_AGENT_OUTPUT_TEMPLATE: 'Saved skill package file:',
    LOG_AGENT_CAPTION_TEMPLATE: 'Saved agent caption copy:',
    LOG_AGENT_METRICS_TEMPLATE: 'Saved agent metrics:',
    LOG_AGENT_PACKAGE_TEMPLATE: 'Skill package root:',
    LOG_AGENT_SKILL_DIRS_TEMPLATE: 'Skill directories:',
    AGENT_FOLDER_NAME: 'agents',
    AGENT_METRICS_EXTENSION: 'metrics.json',
    AGENT_CAPTION_EXTENSION: 'transcript.txt',
    AGENT_RAW_RESPONSE_EXTENSION: 'agent-raw.md',
    LOG_AGENT_EMPTY: 'No transcript text generated for local agent',
    LOG_AGENT_STARTED: 'Running local agent:',
  },

  output: {
    MILLISECOND_PAD_WIDTH: 3,
    FIRST_CUE_INDEX: 1,
    MARKDOWN_BULLET_PREFIX: '- ',
    MARKDOWN_HEADER: '# Transcript',
    START_TIME_PREFIX: '[',
    END_TIME_SUFFIX: ']',
    CUE_STEP: 1,
    TAG_REMOVAL_PATTERN: /<[^>]+>/g,
    WHITESPACE_NORMALIZER_PATTERN: /\s+/g,
    TIMESTAMP_CAPTURE_PATTERN:
      /^((?:\d+:)?\d{2}:\d{2}[\.,]\d{3})\s*\-\-\>\s*((?:\d+:)?\d{2}:\d{2}[\.,]\d{3})/,
    TIMESTAMP_BASE_PART_INDEX: 0,
    DEDUPLICATE_KEY_SEPARATOR: '|',
    JSON3_PARSE_ERROR_PREFIX: 'Could not parse JSON3 caption payload',
  },

  playerApi: {
    YOUTUBE_PLAYER_API_PATH: '/youtubei/v1/player',
    HTML5_PREFERENCE: 'HTML5_PREF_WANTS',
    YOUTUBE_INITIAL_CONFIG_MARKER: 'ytcfg.set(',
    SIGNATURE_TIMESTAMP_PATTERN: /(?:signatureTimestamp|sts)\s*:\s*(?<signatureTimestamp>[0-9]{5})/,
    DEFAULT_ANDROID_API_KEY: 'AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w',
    DEFAULT_IOS_API_KEY: 'AIzaSyB-63vPrdThhKuerbB2N_l7Kwwcxj6yUAc',
    LOG_CLIENT_PREFIX: 'player client',
    LOG_CLIENT_EMPTY: 'returned no caption tracks',
    LOG_CLIENT_FAILED: 'failed',
    LOG_STICKY_CLIENT: 'sticky player client',
    // Prefer the client that usually returns tracks first (android before android_vr).
    PREFERRED_CLIENT_ORDER: [
      'android',
      'ios',
      'web',
      'mweb',
      'tv',
      'android_vr',
      'web_embedded',
    ],
  },

  playlist: {
    PLAYLIST_ID_PARAM_PATTERN: /[?&]list=([A-Za-z0-9_-]+)/,
    HAS_PLAYLIST_PARAM_PATTERN: /[?&]list=/,
  },

  skillOutput: {
    SKILL_MARKDOWN_NAME: 'SKILL.md',
    DEFAULT_SKILL_SLUG: 'generated-skill',
    FRONTMATTER_FENCE: '---',
    INVALID_PATH_PATTERN: /(^\/|\\|\.\.)/,
    SKILL_NAME_PATTERN: /^[a-z0-9](?:[a-z0-9-]{0,62}[a-z0-9])?$/,
    NAME_LINE_PATTERN: /^name:\s*["']?([^"'\n#]+)["']?\s*$/m,
    DESCRIPTION_LINE_PATTERN: /^description:\s*["']?(.+?)["']?\s*$/m,
  },

  skillPrompt: {
    LOCAL_SKILL_REFERENCE: 'docs/skill-authoring.md',
    FILE_MARKER_OPEN: '===FILE:',
    FILE_MARKER_CLOSE: '===',
    FILE_END_MARKER: '===END===',
    OPEN_STANDARD_URL: 'https://agentskills.io/specification',
  },
};

export type Constants = typeof CONSTANTS;
